#!/bin/bash
  #
  #
  #       AUTHOR - Raman Sailopal 
  #
  # 
  #       Script to remove user from Cache system
  #
  #
  # Sub-code with the cache commands to execute.
  # \" notation is for quoting of quotation marks.
  #
if [[ "$1" == "" ]]
then
	echo "Please pass the user name as the first parameter"
	exit
fi
cmd()
{
       sleep 2;
       echo "ZN \"%SYS\"";
       sleep 2;
       echo "S X=##Class(Security.Users).Delete(\"$1\")";
       sleep 2;
       echo "H";
}
cmd $1 |csession {{ instname }} -B
